version: '3.4'

services:
  vpn:
    container_name: openconnect-vpn
    build: .
    image: openconnect-vpn
    ports:
      - ${HOST_PORT_1}:${HOST_PORT_1}
      #...
      #- ${HOST_PORT_N}:${HOST_PORT_N}
    environment:
      - URL=${VPN_URL}
      - USER=${VPN_USER}
      - PASSWORD=${VPN_PASSWORD}
      - OPTIONS=${VPN_OPTIONS}
      # To expose VPN service ports outside Docker container setup PORT_MAP_APP_i=<HOST_PORT_i>|<VPN_SERVICE_HOST_PORT_i> env var for each VPN service:
      - PORT_MAP_APP_1=${HOST_PORT_1}|${VPN_SERVICE_HOST_PORT_1}
      #...
      #- PORT_MAP_APP_N=${HOST_PORT_N}|${VPN_SERVICE_HOST_PORT_N}
    networks:
      - default
    privileged: true
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
    security_opt:
      - label:disable
